### ISSUE TITLE
Request problem

### ISSUE THREAD

**Issue by IamNAVI** [YouthTechclub/Web#16]
Nearu pievienot savas izmainas projektam !!! Rrr

**Comment by kangarooo** [comment]
Tu esi izveidojis pieprasījumu pievienot tavas izmaiņas. 
https://github.com/YouthTechclub/Web/pull/18
Tur arī šo komentu var pielikt lai pamanītu ātrāk jo tas ir tavs vienīgais pieprasījums.
Ja tās būs novērtēšanu veicot par projektam noderīgām tad tiks pievienotas un šis tiks aizvērts. Pašlaik nav pārskatīts un tikmēr skaitās atvērts pārskatam un pievienošanai. Kas
